
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: cams_db
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    ports:
      - "8008:8008"
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"

  api_gateway:
    build: ./api_gateway
    ports:
      - "8000:8000"
    depends_on:
      - backend